# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('year', models.IntegerField(db_index=True)),
                ('status', models.CharField(max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'budgets',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('actual', models.BooleanField()),
                ('expense', models.BooleanField()),
                ('item_number', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=512)),
                ('amount', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
            ],
            options={
                'db_table': 'budget_items',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EconomicCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('expense', models.BooleanField()),
                ('chapter', models.CharField(max_length=1)),
                ('article', models.CharField(max_length=2, null=True)),
                ('heading', models.CharField(max_length=9, null=True)),
                ('subheading', models.CharField(max_length=9, null=True)),
                ('description', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
            ],
            options={
                'db_table': 'economic_categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=10, db_index=True)),
                ('level', models.CharField(max_length=20, db_index=True)),
                ('name', models.CharField(max_length=200, db_index=True)),
                ('slug', models.SlugField()),
                ('language', models.CharField(max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FunctionalCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('area', models.CharField(max_length=1)),
                ('policy', models.CharField(max_length=3, null=True)),
                ('function', models.CharField(max_length=5, null=True)),
                ('programme', models.CharField(max_length=5, null=True)),
                ('subprogramme', models.CharField(max_length=7, null=True)),
                ('description', models.CharField(max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
            ],
            options={
                'db_table': 'functional_categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FundingCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('expense', models.BooleanField()),
                ('source', models.CharField(max_length=1)),
                ('fund_class', models.CharField(max_length=2, null=True)),
                ('fund', models.CharField(max_length=5, null=True)),
                ('description', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
            ],
            options={
                'db_table': 'funding_categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GeographicCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
            ],
            options={
                'db_table': 'geographic_categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('language', models.CharField(max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'glossary_terms',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uid', models.CharField(max_length=20, db_index=True)),
                ('goal_number', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('report', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
                ('functional_category', models.ForeignKey(to='budget_app.FunctionalCategory', db_column=b'functional_category_id')),
            ],
            options={
                'db_table': 'goals',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GoalActivity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('activity_number', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(to='budget_app.Goal')),
            ],
            options={
                'db_table': 'goal_activities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GoalIndicator',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('indicator_number', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=800)),
                ('unit', models.CharField(max_length=20)),
                ('target', models.BigIntegerField()),
                ('actual', models.BigIntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(to='budget_app.Goal')),
            ],
            options={
                'db_table': 'goal_indicators',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='InflationStat',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('year', models.IntegerField()),
                ('inflation', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inflation_stats',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='InstitutionalCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('institution', models.CharField(max_length=5)),
                ('section', models.CharField(max_length=8, null=True)),
                ('department', models.CharField(max_length=11, null=True)),
                ('description', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
            ],
            options={
                'db_table': 'institutional_categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('actual', models.BooleanField()),
                ('project_id', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
                ('functional_category', models.ForeignKey(db_column=b'functional_category_id', to='budget_app.FunctionalCategory', null=True)),
                ('geographic_category', models.ForeignKey(db_column=b'geographic_category_id', to='budget_app.GeographicCategory', null=True)),
            ],
            options={
                'db_table': 'investments',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MainInvestment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('project_id', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('image_URL', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=20)),
                ('entity_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_year', models.IntegerField(null=True)),
                ('expected_end_year', models.IntegerField(null=True)),
                ('actual_end_year', models.IntegerField(null=True)),
                ('total_expected_amount', models.BigIntegerField()),
                ('already_spent_amount', models.BigIntegerField()),
                ('current_year_amount', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
                ('functional_category', models.ForeignKey(to='budget_app.FunctionalCategory', db_column=b'functional_category_id')),
                ('geographic_category', models.ForeignKey(db_column=b'geographic_category_id', to='budget_app.GeographicCategory', null=True)),
            ],
            options={
                'db_table': 'main_investments',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('area', models.CharField(max_length=100, null=True, db_index=True)),
                ('programme', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('payee', models.CharField(max_length=200, db_index=True)),
                ('payee_fiscal_id', models.CharField(max_length=15, db_index=True)),
                ('anonymized', models.BooleanField(default=False)),
                ('expense', models.BooleanField()),
                ('description', models.CharField(max_length=300)),
                ('amount', models.BigIntegerField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(to='budget_app.Budget')),
                ('economic_category', models.ForeignKey(db_column=b'economic_category_id', to='budget_app.EconomicCategory', null=True)),
                ('functional_category', models.ForeignKey(db_column=b'functional_category_id', to='budget_app.FunctionalCategory', null=True)),
                ('institutional_category', models.ForeignKey(db_column=b'institutional_category_id', to='budget_app.InstitutionalCategory', null=True)),
            ],
            options={
                'db_table': 'payments',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PopulationStat',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('year', models.IntegerField()),
                ('population', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(to='budget_app.Entity', db_column=b'entity_id')),
            ],
            options={
                'db_table': 'population_stats',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='goal',
            name='institutional_category',
            field=models.ForeignKey(to='budget_app.InstitutionalCategory', db_column=b'institutional_category_id'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='economic_category',
            field=models.ForeignKey(to='budget_app.EconomicCategory', db_column=b'economic_category_id'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='functional_category',
            field=models.ForeignKey(to='budget_app.FunctionalCategory', db_column=b'functional_category_id'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='funding_category',
            field=models.ForeignKey(to='budget_app.FundingCategory', db_column=b'funding_category_id'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='institutional_category',
            field=models.ForeignKey(to='budget_app.InstitutionalCategory', db_column=b'institutional_category_id'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='budget',
            name='entity',
            field=models.ForeignKey(to='budget_app.Entity', db_column=b'entity_id'),
            preserve_default=True,
        ),
    ]
